============================= test session starts ==============================
platform linux -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
Using --random-order-bucket=global
Using --random-order-seed=556879

rootdir: /sandbox
plugins: cov-2.11.1, mock-3.5.1, random-order-1.0.4
collecting ... collected 3 items

test_fizz_buzz.py::test_empty_list FAILED                                [ 33%]
test_fizz_buzz.py::test_one_item FAILED                                  [ 66%]
test_fizz_buzz.py::test_first_multiple_of_3 FAILED                       [100%]

=================================== FAILURES ===================================
_______________________________ test_empty_list ________________________________

    def test_empty_list():
>       assert fizz_buzz(0) == []

test_fizz_buzz.py:4: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

num_items = 0

    def fizz_buzz(num_items):
        result = [n+1 for n in range(num_items)]
    
>       for i in len(num_items):
E       TypeError: object of type 'int' has no len()

fizz_buzz.py:12: TypeError
________________________________ test_one_item _________________________________

    def test_one_item():
>       assert fizz_buzz(1) == [1]

test_fizz_buzz.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

num_items = 1

    def fizz_buzz(num_items):
        result = [n+1 for n in range(num_items)]
    
>       for i in len(num_items):
E       TypeError: object of type 'int' has no len()

fizz_buzz.py:12: TypeError
___________________________ test_first_multiple_of_3 ___________________________

    def test_first_multiple_of_3():
>       assert fizz_buzz(3) == [1, 2, 'Fizz']

test_fizz_buzz.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

num_items = 3

    def fizz_buzz(num_items):
        result = [n+1 for n in range(num_items)]
    
>       for i in len(num_items):
E       TypeError: object of type 'int' has no len()

fizz_buzz.py:12: TypeError
=========================== short test summary info ============================
FAILED test_fizz_buzz.py::test_empty_list - TypeError: object of type 'int' h...
FAILED test_fizz_buzz.py::test_one_item - TypeError: object of type 'int' has...
FAILED test_fizz_buzz.py::test_first_multiple_of_3 - TypeError: object of typ...
============================== 3 failed in 0.08s ===============================
